enum class Materiel_Type{
    WALL,BABA,LAVA,ROCK,ICE,GRASS,IS,YOU,FLAG,TEXT_YOU,TEXT_WALL,TEXT_LAVA,
    TEXT_ICE,TEXT_GRASS,TEXT_BABA,TEXT_HOT,PUSH,SINK,STOP,
    EMPTY,TEXT_EMPTY,SKULL,TEXT_SKULL,TEXT_FALG,WIN,TEXT_WOTER,WATER,KILL
};
