#ifndef TYPE_H
#define TYPE_H

enum class Type{
    WALL,TEXT_WALL,
    BABA,TEXT_BABA,
    /*YOU,*/TEXT_YOU,
    LAVA,TEXT_LAVA,
    WATER,TEXT_WATER,
    ROCK,TEXT_ROCK,
    ICE,TEXT_ICE,
    GRASS,TEXT_GRASS,
    SKULL,TEXT_SKULL,
    FLAG,TEXT_FALG,
    TEXT_HOT,
    IS,
    EMPTY,TEXT_EMPTY,
};


#endif // TYPE_H
